config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "users#index"

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :new, :create, :show, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:create]
    end
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  namespace :api do
    resources :users, only: [:index] do
      resources :posts, only: [:index]
    end
    resources :posts, only: [:show] do
      resources :comments, only: [:index]
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Abilities for all users
    can :read, :all

    # Abilities for authenticated users
    return unless user.present?

    can :manage, Post, author_id: user.id
    can :create, Comment
    can :manage, Comment, user_id: user.id
    can :destroy, Like, user_id: user.id

    # Abilities for admin users
    can :manage, :all if user.admin?
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  after_save :update_comments_counter
  after_create :set_user_id

  private

  def update_comments_counter
    post.increment!(:comments_counter)
  end

  def set_user_id
    update!(user_id: Current.user.id)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user

  after_save :update_likes_counter

  private

  def update_likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy

  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :likes

  after_save :update_posts_counter

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def five_recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  private

  def update_posts_counter
    author.increment!(:posts_counter)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: 'author_id'
  has_many :comments
  has_many :likes

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def three_recent_posts
    posts.where(author: self).order(created_at: :desc).limit(3)
  end

  def admin?
    role == 'admin'
  end
end

app/models/view.rb
class View < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/api/comments_controller.rb
class Api::CommentsController < ApplicationController
  def index
    @post = Post.find(params[:post_id])
    @comments = @post.comments
    render json: @comments
  end
end

app/controllers/api/posts_controller.rb
class Api::PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts
    render json: @posts
  end

  def show
    @post = Post.find(params[:post_id])
    render json: @post
  end

  def create_comment
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    render json: @comment, status: :created
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }

    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource
  layout 'boilerplate'
  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.user = current_user
    if @comment.save
      flash[:success] = 'Comment added successfully!'
      redirect_to user_post_path(id: @comment.post_id, user_id: @comment.user_id)
    else
      flash.now[:error] = 'Error: Comment could not be saved!'
      render :new, locals: { comment: @comment }
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.post.decrement!(:comments_counter)
    @comment.destroy!
    flash[:success] = 'Comment deleted.'
    redirect_to user_post_path(id: @comment.post_id, user_id: @comment.user_id)
  end

  private

  def comment_params
    params.require(:comment).permit(:text, :user_id, :post_id)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  layout 'boilerplate'
  def create
    @like = Like.new(post_id: params[:post_id], user_id: params[:user_id])
    @like.user = current_user
    if @like.save
      flash[:success] = 'Liked the Post!'
      redirect_to user_post_path(id: @like.post_id, user_id: @like.user_id)
    else
      flash.now[:error] = 'Like to the Post could not be saved!'
    end
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  before_action :authenticate_user!, except: :index
  def index; end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
  layout 'boilerplate'
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:comments).order(id: :asc)
    @posts = @posts.paginate(page: params[:page], per_page: 2)
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.author = current_user
    if @post.save
      flash[:success] = 'Post added Successfully!'
      redirect_to user_posts_url
    else
      flash.now[:error] = 'Error: Post could not be saved!'
      render :new, locals: { post: @post }
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.author.decrement!(:posts_counter)
    @post.comments.destroy_all
    @post.likes.destroy_all
    @post.destroy!
    flash[:success] = 'Post Deleted!'
    redirect_to user_posts_url
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout 'boilerplate'
  def index
    @users = User.order(id: :asc)
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<h2>Add a Comment!</h2>

<% flash.each do |name, message| -%>
    <div class="<%= name %>-flash">
      <%= message %>
    </div>
<% end -%>

<%= form_with model: [:user, :post, @comment], local: true, class: 'comment-form' do |form| %>
    <div>
      <%= form.label :text %>
      <%= form.text_area :text %>
      <%= form.hidden_field :user_id, value: params[:user_id] %>
      <%= form.hidden_field :post_id, value: params[:post_id] %>
      <%= form.submit "Add Comment" %>
    </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav>
  <button id='back-button'><%= link_to "Home", root_path %></button>
  <h1>Blog App</h1>
  <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "sign-out" %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectBlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/layouts/boilerplate.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectBlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "style", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/likes/_like_post.html.erb
<%= form_with(model: @like, url: user_post_likes_path(user_id: post.author_id, post_id: post.id), local: true, class: 'like-form') do |form| %>
    <div>
      <%= form.hidden_field :user_id, value: :user_id %>
      <%= form.hidden_field :post_id, value: :post_id %>
      <%= form.submit "Like Post" %>
    </div>
<% end %>

app/views/login/index.html.erb
# login index page

app/views/posts/_post_data.html.erb
<div id="each-post-info">
    <h3 id="post-title"><%= link_to "#{post.title} ##{i}", user_post_path(@user, post) %></h3>
    <p id="post-text"><%= truncate(post.text, length: 100, omission: '.....') %></p>
    <div id="post-counts">
        <p id="count-text">Comments: <%= post.comments_counter %>, Likes: <%= post.likes_counter %></p>
    </div>
</div>

app/views/posts/index.html.erb
<div id="user-all-posts">
    <%= render partial: "users/user_data", locals: { user: @user } %>

    <% flash.each do |name, message| -%>
        <div class="<%= name %>-flash">
          <%= message %>
        </div>
    <% end -%>

    <% if (current_user.id == @user.id) && (can? :create, Post) %>
      <h2 class="add-post"><%= link_to 'Add new Post', new_user_post_path %></h2>
    <% end %>

    <div id="posts-container">
        <% @posts.each_with_index do |post, i| %>
            <% five_recent_comments = post.five_recent_comments.includes(:user) %>
            <div class="each-post-container">
                <%= render partial: "posts/post_data", locals: { post: post, i: i + 1 } %>
                <div id="post-comments">
                    <% if five_recent_comments.empty? %>
                        <p class="each-comment">No Comments found!</p>
                    <% else %>
                        <% five_recent_comments.each do |comment|%>
                            <p class="each-comment">@<%= comment.user.name %>: <%= comment.text %></p>
                        <% end %>
                    <% end %>
                </div>
            </div>
        <% end %>
    </div>

    <%= will_paginate %>
</div>

app/views/posts/new.html.erb
<h2>Add a new Post.<h2>

<% flash.each do |name, message| -%>
    <div class="<%= name %>-flash">
      <%= message %>
    </div>
<% end -%>

<%= form_with model: [:user, @post], local: true, class: 'post-form' do |form| %>
    <div>
      <%= form.label :title %>
      <%= form.text_field :title %>
      <%= form.label :text %>
      <%= form.text_area :text %>
      <%= form.submit "Add Post" %>
    </div>
<% end %>
      

app/views/posts/show.html.erb
<div class="post-container">
    <div id="post-content">
        <div id="name-counts">
        <p id="each-post-name"><%= @post.title %> by <%= @post.author.name %></p>
        <p id="each-post-c-l">Comments: <%= @post.comments_counter %>, Likes: <%= @post.likes_counter %></p>
        </div>
        <p id="each-post-text"><%= @post.text %></p>
    </div>

    <%= render partial: "likes/like_post", locals: {post: @post} %>

    <div id="comments-container">
        <% if @post.comments.empty? %>
            <p class="each-commnet">No comments yet!</p>
        <% else %>
            <% @post.comments.each do |comment| %>
                <div class='comment-delete'>
                 <p class="each-comment">@<%= comment.user.name %>: <%= comment.text %></p>

                 <% if can? :destroy, comment %>
                   <%= form_with(model: comment, url: user_post_comment_path(@post.author, @post, id: comment.id), method: :delete, id: 'delete-comment-form') do |form| %>
                    <%= form.submit "Delete Comment", id: 'delete-comment-submit' %>
                   <% end %>
                 <% end %>
                </div>
            <% end %>
        <% end %>
    </div>

    <% flash.each do |name, message| -%>
        <div class="<%= name %>-flash">
          <%= message %>
        </div>
    <% end -%>

    <% if can? :create, Comment %>
      <h2 class="add-comment"><%= link_to 'Comment on the Post!', new_user_post_comment_path(@post.author, @post) %><h2>
    <% end %>

    <% if can? :destroy, @post %>
        <%= form_with(model: @post, url: user_post_path(@post.author, @post), method: :delete, id: 'delete-post-form') do |form| %>
            <%= form.submit "Delete Post", id: 'delete-post-submit' %>
        <% end %>
    <% end %>
</div>

app/views/users/_user_data.html.erb
<div class= "user-data-block">
    <img class="user-img" src="<%= user.photo %>" alt="User photo">
    <div class="name-posts-count">
        <h2 class="user-name"><%= link_to user.name, user_path(user) %></h2>
        
        <div class="user-posts-count"><p>Number of posts: <%= user.posts_counter %></p></div>
    </div>
</div>

app/views/users/index.html.erb
<div id="users-container">
    <% @users.each do |user| %>
        <%= render partial: "users/user_data", locals: { user: user } %>
    <% end %>
</div>

app/views/users/show.html.erb
<div id="user-posts-container">
    <%= render partial: "users/user_data", locals: { user: @user } %>
    <div id="user-bio">
        <h3>Bio</h3>
        <p id="bio"><%= @user.bio %></p>
    </div>
    <% if @user.posts_counter.zero? %>
        <div class='user-data-block'>No posts were added by the User yet!</div>
        <% if (current_user.id == @user.id) && (can? :create, Post) %>
          <h2 class="add-post"><%= link_to 'Add new Post', new_user_post_path(@user) %></h2>
        <% end %>
    <% else %>
        <div id="user-recent-posts">
            <% @user.three_recent_posts.each_with_index do |post, i| %>
                <%= render partial: "posts/post_data", locals: { post: post, i: i + 1 } %>
            <% end %>
        </div>

        <div id="all-posts"><a href="<%= user_posts_path(@user) %>">See all posts</a></div>
    <% end %>
</div>